[package]
name = "sarc"
version = "0.0.1"
description = "Reads SARC files. A commonly used Nintendo file format."
authors = ["Mario Reder <mreder1289@gmail.com>"]
license = "MIT/Apache-2"
edition = "2018"

[dependencies]
num_enum = "0.4"
tar = { version = "0.4", optional = true }

[dev-dependencies]
test-case = "1.0"

[features]
default = []
tar_sarc = ["tar"]

[profile]
[profile.dev]
opt-level = 1

[profile.release]
debug = false
lto = true
codegen-units = 1
