on: [push, pull_request]

name: Continuous Integration Cli

env:
  CRATE_PATH: ninres-cli

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - 1.42.0
        experimental: [false]
        include:
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: -p ${{ env.CRATE_PATH }}

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: -p ${{ env.CRATE_PATH }}

      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: -p ${{ env.CRATE_PATH }} -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -p ${{ env.CRATE_PATH }} -- -D warnings

  publish:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: beta
          override: true

      - name: Check version
        run: |
          cargo install cargo-whatfeatures --no-default-features --features "rustls"
          export LIB_VERSION=$(cat $CRATE_PATH/Cargo.toml | grep version | head -1 | sed 's/[",(version = )]//g')
          echo LIB_VERSION=$LIB_VERSION
          export CRATE_VERSION_EXISTS=$(NO_COLOR=1 ./crate_version_exists.sh $LIB_VERSION $CRATE_PATH)
          echo CRATE_VERSION_EXISTS=$CRATE_VERSION_EXISTS

      - name: Deploy to Crates.io
        env:
          CARGO_CREDENTIALS: ${{ secrets.CARGO_CREDENTIALS }}
        run: bash crate_publish.sh $CRATE_PATH
        continue-on-error: true
